CREATE DATABASE SP_Med_Group
GO

USE SP_Med_Group
GO

	CREATE TABLE TIPOUSUARIO (
	idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
	nomeTipoUsuario VARCHAR (50) NOT NULL UNIQUE,
);
GO

	CREATE TABLE SITUACAO (
	idSituacao TINYINT PRIMARY KEY IDENTITY,
	nomeSituacao VARCHAR (50) NOT NULL UNIQUE
	);
	GO

	CREATE TABLE ESPECIALIDADE(
	idEspecialidade TINYINT PRIMARY KEY IDENTITY,
	nomeEspecialidade VARCHAR (100) NOT NULL UNIQUE
	);
	GO

	CREATE TABLE CLINICA (
	idClinica SMALLINT PRIMARY KEY IDENTITY,
	nomeFantasia VARCHAR(55) DEFAULT 'NOME FANTASIA NÃO CADASTRADO',
	cnpj VARCHAR (20) UNIQUE NOT NULL,
	razaoSocial VARCHAR (200)  NOT NULL,
	endereco VARCHAR (300)  NOT NULL,
	telefone CHAR(15) UNIQUE,
	email VARCHAR (255) NOT NULL UNIQUE,
	);
	GO

	CREATE TABLE USUARIO (
	idUsuario BIGINT PRIMARY KEY IDENTITY,
	idTipoUsuario  TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO (idTipoUsuario),
	nomeUsuario VARCHAR(150) NOT NULL,
	email VARCHAR (256)  NOT NULL,
	senha VARCHAR (100)  CHECK (len (senha)>= 8) NOT NULL,
	); 
	GO

	CREATE TABLE PACIENTE(
	idPaciente BIGINT PRIMARY KEY IDENTITY,
	idUsuario BIGINT FOREIGN KEY REFERENCES USUARIO (idUsuario),
	nomePaciente VARCHAR(300) DEFAULT 'NOME NÃO DECLARADO',  
	telefone VARCHAR(30) DEFAULT 'TELEFONE NÃO CADASTRADO',
	dataNascimento SMALLDATETIME NOT NULL,
	rg CHAR(10) NOT NULL UNIQUE,
	cpf CHAR(11) UNIQUE NOT NULL,
	endereco VARCHAR (300) NOT NULL
	);
	GO

	CREATE TABLE MEDICO(
	idMedico BIGINT PRIMARY KEY IDENTITY,
	idUsuario BIGINT FOREIGN KEY REFERENCES USUARIO (idUsuario),
	idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA (idClinica),
	idEspecialidade TINYINT FOREIGN KEY REFERENCES ESPECIALIDADE (idEspecialidade),
	nomeMedico VARCHAR(300) DEFAULT 'DR NÃO CADASTRADO',
	crm VARCHAR (10) NOT NULL UNIQUE
	);
	GO


	CREATE TABLE CONSULTA (
	idConsulta BIGINT PRIMARY KEY IDENTITY,
	idPaciente bigINT FOREIGN KEY REFERENCES PACIENTE (idPaciente),
	idMedico BIGINT FOREIGN KEY REFERENCES MEDICO (idMedico),
	idSituacao TINYINT FOREIGN KEY REFERENCES SITUACAO (idSituacao),
	dataConsulta DATETIME NOT NULL,
	descricao VARCHAR (500) DEFAULT 'Consulta sem descrição'
	);
	GO

	CREATE TABLE FOTOPERFIL (
	idFotoPerfil INT PRIMARY KEY IDENTITY,
	idUsuario BIGINT FOREIGN KEY REFERENCES USUARIO(idUsuario),
	nomeArquivo VARCHAR(150) UNIQUE 
);
GO