CREATE DATABASE SP_Med_Group
GO

USE SP_Med_Group
GO

	CREATE TABLE TIPOUSUARIO (
	idTipoU TINYINT PRIMARY KEY,
	nomeTipoU VARCHAR(15)
	)
	GO

	CREATE TABLE SITUACAO (
	idSituacao TINYINT PRIMARY KEY,
	nomeSituacao VARCHAR (10)
	);
	GO

	CREATE TABLE ESPECIALIDADE(
	idEspecialidade TINYINT PRIMARY KEY,
	nomeEspecialidade VARCHAR 
	);
	GO

	CREATE TABLE CLINICA (
	idClinica TINYINT PRIMARY KEY,
	nomeClinica VARCHAR(30) UNIQUE NOT NULL,
	cnpj VARCHAR (20) UNIQUE NOT NULL,
	RazaoSocial VARCHAR (20) UNIQUE NOT NULL,
	endereco VARCHAR (300) UNIQUE NOT NULL,
	telefone CHAR(9) UNIQUE NOT NULL
	);
	GO

	CREATE TABLE USUARIO (
	idUsuario BIGINT PRIMARY KEY,
	idTipoU  TINYINT FOREIGN KEY REFERENCES TIPOUSUARIO (idTipoU),
	email VARCHAR (256) UNIQUE NOT NULL,
	senha VARCHAR (100) NOT NULL CHECK (len (senha)>= 8),
	); 
	GO

	CREATE TABLE PACIENTE(
	idPaciente BIGINT PRIMARY KEY IDENTITY,
	idUsuario BIGINT FOREIGN KEY REFERENCES USUARIO (idUsuario),
	nomePaciente VARCHAR(300) NOT NULL,  
	telefone VARCHAR(20) UNIQUE,
	dataNasc DATE NOT NULL,
	rg CHAR(12) NOT NULL,
	cpf CHAR(14) UNIQUE NOT NULL,
	endereco VARCHAR (300) NOT NULL
	);
	GO

	CREATE TABLE MEDICO(
	idMedico BIGINT PRIMARY KEY IDENTITY (1,1),
	idUsuario BIGINT FOREIGN KEY REFERENCES USUARIO (idUsuario),
	idClinica TINYINT FOREIGN KEY REFERENCES CLINICA (idClinica),
	idEspecialidade TINYINT FOREIGN KEY REFERENCES ESPECIALIDADE (idEspecialidade),
	nomeMedico VARCHAR(300) NOT NULL,
	crm CHAR (8) NOT NULL
	);
	GO


	CREATE TABLE CONSULTA (
	idConsulta BIGINT PRIMARY KEY IDENTITY,
	idPaciente BIGINT FOREIGN KEY REFERENCES PACIENTE (idPaciente),
	idMedico BIGINT FOREIGN KEY REFERENCES MEDICO (idMedico),
	idSituacao TINYINT FOREIGN KEY REFERENCES SITUACAO (idSituacao),
	dataConsulta DATETIME NOT NULL,
	descricao VARCHAR (500) NOT NULL
	);
	GO